### ISSUE TITLE
<Esc> is mapped to <Nop>

### ISSUE THREAD

**Issue by ryvnf** [ryvnf/readline.vim#2]
Escape is currently mapped to do nothing in the plugin This is to prevent an invalid meta-mapping from closing the command line. A user on IRC has requested that <Esc> should not be remapped.

I personally think that pressing an invalid meta-mapping (like M-v when user meant to press M-b) closing or running the command-line can be very frustrating, which is the motivation for mapping it to `<Nop>`. I also think that people generally press ENTER to run the command, or CTRL-C to cancel it (but that is only from my experience, and might be wrong).

I mainly see two possible solutions for this:

1. Adding an option (like `g:readline_esc_nop`) which allows the user to explicitly get the behavior they want.

2. Creating a mapping for `<Esc><Esc>` which emulates the single `<Esc>` press. This would require reading the `x`-flag in `'cpoptions'`, and would require checking if a custom mapping should be run when pressing this key combination.

3. Not mapping ESC and encouraging user to map `<Esc>` to `<Nop>` in their vimrc if this is a problem.

Of these two solution, I think number 1 is to be preferred, as it is simple. I personally don't like number 3, as I like the current behavior (but I would be open to implement it if enough other people would prefer it).

I also don't know how many other people dislike remapping ESC, so this might not be a problem. But I assume the user on IRC can't be the only one.

**Comment by nickspoons** [comment]
Hi @ryvnf, it was me that suggested removing the `cnoremap <Esc> <Nop>` mapping on IRC.

Since then I've been really enjoying the plugin. I have caught myself hitting `<Esc>` and realising it didn't work so using `<C-c>` instead - but I actually think I'm happy with it this way after all.

I still think that some users are going to prefer to be able to `<Esc>` out of the command line, so I would vote for option 1.

**Comment by ryvnf** [comment]
Thanks.

If option 1 is to be implemented, it can be done in two ways:

1. When the option is turned off, it will simply not do `cnoremap <Esc> <Nop>`. Doing it this way would make the key have to time out `'timeoutlen'` milliseconds (default 1000). I think this is less than ideal.

2. When the option is turned off, it will remove the ESC-mapping and replace all `<Esc>` mappings with equivalent function-key mappings. This works by setting a unused function key to the map combination, and mapping through the function key instead of the ESC mapping directly. This is a hack which @nickspoons briefly mentioned on IRC, and is used in [rsi.vim](https://github.com/tpope/vim-rsi) to avoid having to map `<Esc>`. In my observation this will remove the timeout. But it would introduce weird hacks in the script, and add to the overall complexity (which I would rather avoid). It also relies around setting global options which likely would cause unexpected incompatibilities with other plug-ins doing something similar. The plug-in also currently uses 19 (12 without uppercase meta-mappings) meta-mappings. Which would require using 19 of the 37 mappable function keys. But this way would be cleaner to a user, who actively uses `<Esc>`.

I will keep this issue open, and wait until at-least one more person requests removing the no-operation ESC-mapping until any change will be applied.

**Comment by louwers** [comment]
I would really appreciate the option to be able to quit the command line with `<Esc>`, so consider me to be that one more person.

**Comment by ryvnf** [comment]
Hello @louwers. Thanks for your feedback.

This plug-in doesn't have many users, so seeing two people requesting this is probably an indication that a large percentage want this.

Then there is the question of how it should be implemented, raised in the post above. I will also see if there is a way to get around the map timeout for escape, without using the function-key definition hacks described above.

**Comment by ryvnf** [comment]
I've experimented with using keycodes to avoid the timeout on `<Esc>` and created a branch [readline_esc](https://github.com/ryvnf/readline.vim/blob/readline_esc/plugin/readline.vim) to change the behavior. I've found that it is possible to set arbitrary termcap-codes which can be used to avoid changing the codes of existing keys, so the number of keys to map is not a problem.

Using the key-code hacks has two major drawbacks:

1. Only one plug-in can use the hack for a particular mapping at the same time, even if the other plug-in uses it in a different mode it won't work
2. It causes problems with everyday macro recordings. This is probably due to a bug in Vim. But doing the trick means that recordings like `ihello<Esc>b` will be interpreted as `ihello<t_xy>` which already caused great problems developing the plug-in

Especially the 2nd drawback is so serious that I don't think it is worth it. Probably better to simply remove the `<Esc>` to `<Nop>` binding.

**Comment by ryvnf** [comment]
I found a new method to get the desired behavior.

Using a combination of `<nowait>` and `getchar()` it is possible to make Escape exit the command-line if it gets pressed alone but not when it is pressed as part of a Meta-chord using Alt. This is a much cleaner solution that doesn't suffer from the problems as the solution listed above.

The work is on the [readline_esc branch](https://github.com/ryvnf/readline.vim/tree/readline_esc). Will probably merge this feature when I have gotten the time to test it and document it.
