### ISSUE TITLE
Does not work together with :paste

### ISSUE THREAD

**Issue by parisni** [ryvnf/readline.vim#9]
so far, when :paste is run then this stops working

**Comment by ryvnf** [comment]
I think this will be a tough one to fix. From `:help 'paste'` (bold emphasis mine):

> When the 'paste' option is switched on (also when it was already on):
> 	- **mapping in Insert mode and Command-line mode is disabled**
> 	- abbreviations are disabled
> 	- 'autoindent' is reset

This is basically what `'paste'` is supposed to do, disable all mappings so text can be pasted verbatim.

I do not think there is any reasonable way to get around this.

**Comment by parisni** [comment]
yeah, this makes sense. thanks for the explanations.
